create table if not exists public.vessels (
  mmsi text primary key check (mmsi ~ '^[0-9]{9}$'),
  name text not null,
  color text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.vessel_positions (
  id bigint generated by default as identity primary key,
  mmsi text not null references public.vessels(mmsi) on delete cascade,
  latitude double precision not null check (latitude between -90 and 90),
  longitude double precision not null check (longitude between -180 and 180),
  course double precision,
  speed_knots double precision not null default 0,
  navigation_status integer,
  received_at timestamptz not null,
  captured_at timestamptz not null,
  source text not null default 'mock',
  unique (mmsi, received_at)
);

create index if not exists vessel_positions_mmsi_received_idx
  on public.vessel_positions (mmsi, received_at desc);

alter table public.vessels enable row level security;
alter table public.vessel_positions enable row level security;

drop policy if exists "Public fleet read" on public.vessels;
create policy "Public fleet read" on public.vessels for select using (true);

drop policy if exists "Public position read" on public.vessel_positions;
create policy "Public position read" on public.vessel_positions for select using (true);

insert into public.vessels (mmsi, name, color) values
  ('247520340', 'Isera', '#ff7a45'),
  ('240576800', 'Fizzy', '#46d6bd'),
  ('240608700', 'Tiamat', '#73a7ff')
on conflict (mmsi) do update set name = excluded.name, color = excluded.color;

insert into public.vessel_positions
  (mmsi, latitude, longitude, course, speed_knots, navigation_status, received_at, captured_at, source)
values
  ('247520340', 37.69530, 24.06022, null, 0, 15, '2026-07-21T12:00:00Z', '2026-08-04T21:20:00Z', 'mock'),
  ('240576800', 37.69558, 24.05911, null, 0, 5, '2026-08-04T19:19:23Z', '2026-08-04T21:20:00Z', 'mock'),
  ('240608700', 37.93695, 23.65940, null, 0, 15, '2026-06-30T12:00:00Z', '2026-08-04T21:20:00Z', 'mock')
on conflict (mmsi, received_at) do update set
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  course = excluded.course,
  speed_knots = excluded.speed_knots,
  navigation_status = excluded.navigation_status,
  captured_at = excluded.captured_at,
  source = excluded.source;

